### ISSUE TITLE
Generated cpp file 

### ISSUE THREAD

**Issue by antonymarion** [fayolle/csg_recovery#1]
Hi and thanks to publish this code,

I just tested and get some results, I wanted to visualize it but I am afraid some headers are missing, right?

```
#include "operations.h"
#include "primitives.h"

```

Do you have any out of the box tool to render the produced test.cpp file?

Regards,
Antony

**Comment by fayolle** [comment]
@antonymarion The files "primitives.h" and "operations.h" are in the sub-directory "utils". 
The generated C++ file (the one that you obtained in step 3, and that includes the two headers above) defines an implicit surface (a 'pseudo'-SDF). To obtain a triangle mesh (for visualization), you can use the Marching Cubes algorithm (or any variant).

**Comment by fayolle** [comment]
@antonymarion An alternative is to sample the function (in the generated C++ file) on a regular grid, export the result as a VTK file and visualize the zero level-set with the software [Paraview](https://www.paraview.org/).

There is a  script in the file "utils/create_vtk_regular_grid.py" that can be used for generating the VTK file. Go to the "utils" directory and then: 
```
python create_vtk_regular_grid.py ../test-segmented.fit ../test_expression.txt test.cpp ../test.xyz test.vtk
``` 
The Python script is ugly: It assumes that g++ is available and calls it with the 'system' command, but it could be a 'cheap' way to visualize the result.
